config/routes.rb
Rails.application.routes.draw do

  root to: "users/interactions#index"

  resources :referrals, only: [:index] do
    collection do
      post 'mark'
      get 'confirmed'
    end
  end

  namespace :users do
    resources :interactions, only: [:index, :show, :new, :create] do
      scope module: 'interactions' do
        resources :events, only: [:create]
      end
    end

    resources :clients, only: [:edit, :update, :index, :new, :create]
    resources :services, only: [:index]
    resources :referrals, only: [:new, :create, :show, :update]
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :phone, presence: true, uniqueness: true

  has_many :interactions

  def self.with_phone(search)
    normalized_phone = search.to_s.length == 10 ? "+1"+search : search

    where(phone: normalized_phone).first || new(phone: search.to_s)
  end

  def male?
    ["man", "male", "guy", "dude"].include? gender.to_s.downcase
  end

  def female?
    ["woman", "female", "lady"].include? gender.to_s.downcase
  end

  def ssn?
    ssn.present?
  end

  def family?
    kid_count.to_i > 0
  end

  def name
    "#{first_name} #{last_name}"
  end

  def formatted_birthdate
    birthdate && birthdate.strftime("%B %e, %Y")
  end

  def contact_types
    types = interactions.map(&:type).uniq.compact
    types.any? ? types.join(", ") : "No contact types"
  end

  def last_contacted_event
    events = Event.where(interaction: interactions)
    if events.any?
      events.max_by(&:created_at)
    end
  end

  def last_contacted
    if last_contacted_event
      last_contacted_event.created_at.strftime("%m/%d/%Y %l:%M %p")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    # TODO: auth and constrain to user

    def current_user
      @current_user ||= User.first
    end

    helper_method :current_user
  end
end

app/controllers/users/clients_controller.rb
module Users
  class ClientsController < ApplicationController
    def edit
      @client = Client.find(params[:id])
    end

    def update
      @client = Client.find(params[:id])
      if @client.update_attributes(client_params)
        if params["search_path"].present?
          redirect_to users_services_path(service_name: params["search_path"], interaction_id: @client.interactions.last.id)
        else
          redirect_to users_interactions_path
        end
      else
        render :edit
      end
    end

    def index
      @clients = Client.all
    end

    def new
      @client = Client.new
    end

    def create
      @client = Client.new(client_params)
      if @client.save
        redirect_to users_clients_path
      else
        render :new
      end
    end

    private

      def client_params
        params.require(:client).permit(:phone, :first_name, :last_name, :last_address, :gender, :ssn, :ethnicity, :education, :employed, :veteran, :domestic_assault_victim, :mental_health, :kid_count, :birthdate)
      end
  end
end

app/controllers/users/interactions/events_controller.rb
module Users
  module Interactions
    class EventsController < Users::BaseController

      def create
        @event = Event.create({
          user: current_user,
          interaction: current_interaction,
          content: params[:event][:content],
          source_type: source_type_from_commit
        })

        redirect_to [:users, current_interaction]
      end

      private
      def current_interaction
        @current_interaction ||= Interaction.find(params[:interaction_id])
      end
      helper_method :current_interaction

      # HACK
      def source_type_from_commit
        case params[:commit].to_s.downcase
        when "reply"
          then "sms"
        else
          nil
        end
      end
    end
  end
end

app/controllers/users/interactions_controller.rb
module Users
  class InteractionsController < Users::BaseController

    respond_to :html

    def index
      @interactions = Interaction.active_for(current_user).recent.includes(:events)
      @open_interactions = Interaction.no_replies.no_creator.recent.includes(:events)
    end

    def show
      @interaction = Interaction.find(params[:id])
      @client = @interaction.client
      @event = Event.new(interaction: @interaction, user: current_user)
    end

    def new
      client = Client.where(id: params[:client_id]).first
      if interaction = client.interactions.open.first
        redirect_to users_interaction_path(interaction)
      else
        phone = client.phone if client

        @interaction = Interaction.new(phone: phone)
      end
    end

    def create
      @interaction = Interaction.create(params[:interaction].permit(:phone).merge(status: "open", user: current_user))

      respond_with @interaction, location: [:users, @interaction]
    end

  end
end

app/controllers/users/referrals_controller.rb
module Users
  class ReferralsController < Users::BaseController

    respond_to :html

    def new
      @referral = Referral.new(
        code: Referral.generate_code, interaction_id: params[:interaction_id], service_id: params[:service_id])
    end

    def create
      @referral = Referral.create(params[:referral].permit(:code, :interaction_id, :service_id).merge(status: "open"))

      respond_with @referral, location: [:users, current_interaction]
    end

    def show
      @referral = Referral.find(params[:id])
    end

    def update
      @referral = Referral.find(params[:id])
      @referral.update_attributes(status: "resolved")
      @referral.interaction.update_attributes(status: "resolved")
      redirect_to users_interaction_path(@referral.interaction)
    end

    private
    def current_interaction
      @current_interaction ||= Interaction.find(params[:interaction_id] || params[:referral][:interaction_id])
    end
  end
end

app/controllers/users/services_controller.rb
module Users
  class ServicesController < Users::BaseController

    def index
      @services = Service.where(name: params[:service_name].strip)
      @interaction = Interaction.find(params[:interaction_id])
      @services.each{|s|s.qualify_and_disqualify(@interaction.client)}
      @services = @services.sort_by{|s|s.sort_number}
    end
  end

end

app/views/users/clients/_activity_interaction.html.erb
<div class="timeline-item">
  <div class="vert-line"></div>
  <i class="timeline-icon fa <%= icon_class_for_interaction(activity_interaction.type) %>"></i>
  <div class="timeline-text-container">
    <% if activity_interaction.referral.present? && activity_interaction.referral.resolved? %>
      <p class="interaction-status resolved"><i class="resolution-icon small fa fa-check"></i>Resolved</p>
    <% end %>

    <span class="timeline-main-text"><%= type_of_interaction(activity_interaction.type) %></span>
    <% if latest_event = activity_interaction.events.last %>
      <span class="timeline-sub-text"><%= latest_event.created_at.strftime("%m/%d/%Y %l:%M %p") %></span>
    <% end %>
    <span class="timeline-desc"><%= activity_interaction.description %></span>
    <% if activity_interaction.referral %>
      <div class="referral-container">
        <p class="referral-title"><%= activity_interaction.referral.title %></p>
        <p class="referral-note"><%= activity_interaction.referral.note %></p>
        <p class="referral-code"><span class="code-title">Code:</span> <%= activity_interaction.referral.code %></p>

        <% unless activity_interaction.referral.resolved? %>
          <div class="ref-btns">
            <%= link_to "resend", "#", class: "c-btn" %>
            <%= link_to "mark as resolved", users_referral_path(activity_interaction.referral), class: "c-btn" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/clients/_client.html.erb
<li class="interaction-container">
  <% if client.last_contacted_event %>
    <%= link_to users_interaction_path(client.last_contacted_event.interaction) do %>
      <div class='int-class-left'>
        <p class="client-name"><%= client.first_name || client.phone %></p>
        <p class="interaction-data">
          <i class="fa fa-clock-o"></i>
          <span class="title">Last Contacted:</span>
          <%= client.last_contacted %>
        </p>
      </div>
    <% end %>
  <% else %>
    <%= link_to new_users_interaction_path(client_id: client.id) do %>
      <div class='int-class-left'>
        <p class="client-name"><%= client.first_name || client.phone %></p>
        <p class="interaction-data">
          <i class="fa fa-clock-o"></i>
          <span class="title">There hasn't been any interaction with <%= client.first_name || client.phone %> yet.</span>
          <span class="tiny">click to start interaction</span>
        </p>
      </div>
    <% end %>
  <% end %>
</li>

app/views/users/clients/edit.html.erb
<div class="profile-container">
  <%= form_for [:users, @interaction, @client], html: {class: "simple-form"} do |f| %>
    <div class="form-element">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="form-element">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-element">
      <%= f.label :birthdate %>
      <%= f.date_select :birthdate, {order: [:month, :day, :year], prompt: { day: 'Day', month: 'Month', year: 'Year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: false} %>
    </div>
    <div class="form-element">
      <%= f.label :last_address %>
      <%= f.text_field :last_address %>
    </div>
    <div class="form-element">
      <%= f.label :phone %>
      <%= f.phone_field :phone %>
    </div>
    <div class="form-element">
      <%= f.label :gender %>
      <%= f.text_field :gender %>
    </div>
    <div class="form-element">
      <%= f.label :ssn %>
      <%= f.text_field :ssn %>
    </div>
    <div class="form-element">
      <%= f.label :ethnicity %>
      <%= f.text_field :ethnicity %>
    </div>
    <div class="form-element">
      <%= f.label :education %>
      <%= f.text_field :education %>
    </div>
    <div class="form-element">
      <%= f.label :kid_count %>
      <%= f.number_field :kid_count %>
    </div>
    <div class="form-element">
      <%= f.label :employed %>
      <%= f.check_box :employed %>
    </div>
    <div class="form-element">
      <%= f.label :veteran %>
      <%= f.check_box :veteran %>
    </div>
    <div class="form-element">
      <%= f.label :domestic_assault_victim %>
      <%= f.check_box :domestic_assault_victim %>
    </div>
    <div class="form-element">
      <%= f.label :mental_health %>
      <%= f.check_box :mental_health %>
    </div>
    <div class="form-element">
      <%= hidden_field_tag "search_path", params["search_service"] %>
    </div>
    <div class="form-element">
      <!-- column filler -->
    </div>


    <%= f.submit "Submit", class: "c-btn" %>
  <% end %>
</div>

app/views/users/clients/index.html.erb
<div class="container-center">
  <%= link_to "New Client", new_users_client_path, class: "c-btn new-interaction-btn" %>

  <ul class="interactions-container">
    <%= render @clients %>
  </ul>

</div>

app/views/users/clients/new.html.erb
<div class="profile-container">
  <%= form_for [:users, @client], html: {class: "simple-form"} do |f| %>
    <div class="form-element">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="form-element">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-element">
      <%= f.label :birthdate, "Birthday *" %>
      <%= f.date_select :birthdate, {order: [:month, :day, :year], prompt: { day: 'Day', month: 'Month', year: 'Year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: true} %>
    </div>
    <div class="form-element">
      <%= f.label :phone, "Phone *" %>
      <%= f.phone_field :phone %>
    </div>
    <div class="form-element">
      <%= f.label :last_address %>
      <%= f.text_field :last_address %>
    </div>
    <div class="form-element">
      <%= f.label :gender %>
      <%= f.text_field :gender %>
    </div>
    <div class="form-element">
      <%= f.label :ssn %>
      <%= f.text_field :ssn %>
    </div>
    <div class="form-element">
      <%= f.label :ethnicity %>
      <%= f.text_field :ethnicity %>
    </div>
    <div class="form-element">
      <%= f.label :education %>
      <%= f.text_field :education %>
    </div>
    <div class="form-element">
      <%= f.label :kid_count %>
      <%= f.number_field :kid_count %>
    </div>
    <div class="form-element">
      <%= f.label :employed %>
      <%= f.check_box :employed %>
    </div>
    <div class="form-element">
      <%= f.label :veteran %>
      <%= f.check_box :veteran %>
    </div>
    <div class="form-element">
      <%= f.label :domestic_assault_victim %>
      <%= f.check_box :domestic_assault_victim %>
    </div>
    <div class="form-element">
      <%= f.label :mental_health %>
      <%= f.check_box :mental_health %>
    </div>
    <div class="form-element">
      <!-- column filler -->
    </div>

    <%= f.submit "Submit", class: "c-btn" %>
  <% end %>
</div>