config/routes.rb
Rails.application.routes.draw do

  root to: "users/interactions#index"

  resources :referrals, only: [:index] do
    collection do
      post 'mark'
      get 'confirmed'
    end
  end

  namespace :users do
    resources :interactions, only: [:index, :show, :new, :create] do
      scope module: 'interactions' do
        resources :events, only: [:create]
      end
    end

    resources :clients, only: [:edit, :update, :index, :new, :create]
    resources :services, only: [:index]
    resources :referrals, only: [:new, :create, :show, :update]
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :phone, presence: true, uniqueness: true

  has_many :interactions

  def self.with_phone(search)
    normalized_phone = search.to_s.length == 10 ? "+1"+search : search

    where(phone: normalized_phone).first || new(phone: search.to_s)
  end

  def male?
    ["man", "male", "guy", "dude"].include? gender.to_s.downcase
  end

  def female?
    ["woman", "female", "lady"].include? gender.to_s.downcase
  end

  def ssn?
    ssn.present?
  end

  def family?
    kid_count.to_i > 0
  end

  def name
    "#{first_name} #{last_name}"
  end

  def formatted_birthdate
    birthdate && birthdate.strftime("%B %e, %Y")
  end

  def contact_types
    types = interactions.map(&:type).uniq.compact
    types.any? ? types.join(", ") : "No contact types"
  end

  def last_contacted_event
    events = Event.where(interaction: interactions)
    if events.any?
      events.max_by(&:created_at)
    end
  end

  def last_contacted
    if last_contacted_event
      last_contacted_event.created_at.strftime("%m/%d/%Y %l:%M %p")
    end
  end
end

app/controllers/users/clients_controller.rb
module Users
  class ClientsController < ApplicationController
    def edit
      @client = Client.find(params[:id])
    end

    def update
      @client = Client.find(params[:id])
      if @client.update_attributes(client_params)
        if params["search_path"].present?
          redirect_to users_services_path(service_name: params["search_path"], interaction_id: @client.interactions.last.id)
        else
          redirect_to users_interactions_path
        end
      else
        render :edit
      end
    end

    def index
      @clients = Client.all
    end

    def new
      @client = Client.new
    end

    def create
      @client = Client.new(client_params)
      if @client.save
        redirect_to users_clients_path
      else
        render :new
      end
    end

    private

      def client_params
        params.require(:client).permit(:phone, :first_name, :last_name, :last_address, :gender, :ssn, :ethnicity, :education, :employed, :veteran, :domestic_assault_victim, :mental_health, :kid_count, :birthdate)
      end
  end
end

app/views/clients/_client.html.erb
<li class="interaction-container">
  <% if client.last_contacted_event %>
    <%= link_to users_interaction_path(client.last_contacted_event.interaction) do %>
      <div class='int-class-left'>
        <p class="client-name"><%= client.first_name || client.phone %></p>
        <p class="interaction-data">
          <i class="fa fa-clock-o"></i>
          <span class="title">Last Contacted:</span>
          <%= client.last_contacted %>
        </p>
      </div>
    <% end %>
  <% else %>
    <%= link_to clients_path do %>
      <div class='int-class-left'>
        <p class="client-name"><%= client.first_name || client.phone %></p>
        <p class="interaction-data">
          <i class="fa fa-clock-o"></i>
          <span class="title">There hasn't been any interaction with <%= client.name %> yet.</span>
        </p>
      </div>
    <% end %>
  <% end %>
</li>

app/views/clients/_profile_and_timeline.html.erb
<div class="profile-container">

  <div class="profile-top">
    <p class="name"><%= @client.name %></p>
    <p class="top-field"><%= @client.phone %></p>
    <p class="top-field"><%= @client.formatted_birthdate %></p>
    <p class="top-field"><%= [human_readable_text(@client.gender), human_readable_text(@client.ethnicity)].compact.join(" | ") %></p>
    <%= link_to "Edit Client", edit_users_client_path(@client) %>
  </div>

  <%= render "referral" %>

  <div id="profile-toggle-container">
    <%= link_to "Activity Log", "#", class: "profile-toggle-btn active", onclick: "$('.profile-toggle-btn').removeClass('active');$(this).addClass('active');$(this).addClass('active'); $('.client-details-container').removeClass('active'); $('.timeline-container').addClass('active'); return false;" %>
    <%= link_to "Client Details", "#", class: "profile-toggle-btn", onclick: "$('.profile-toggle-btn').removeClass('active');$(this).addClass('active');$(this).addClass('active'); $('.timeline-container').removeClass('active'); $('.client-details-container').addClass('active'); return false;"  %>
  </div>

  <div class="client-details-container">
    <p class="middle-field"><span class="field-title">Last Contacted:</span> <%= @client.last_contacted %></p>
    <p class="middle-field"><span class="field-title">Contacted Via:</span> <%= @client.contact_types %></p>

    <hr>
    <p class="middle-field"><span class="field-title">Veteran:</span> <%= human_readable_boolean(@client.veteran?) %></p>
    <p class="middle-field"><span class="field-title">Domestic Abuse Victim: </span> <%= human_readable_boolean(@client.domestic_assault_victim?) %></p>
    <p class="middle-field"><span class="field-title">Employed:</span> <%= human_readable_boolean(@client.employed?) %></p>
    <p class="middle-field"><span class="field-title">Education Level:</span> <%= human_readable_text(@client.education) %></p>
  </div>

  <div class="timeline-container active">
<!--     <div class="timeline-item">
      <%= link_to "#", class: "new-note-btn" do %>
        <i class="timeline-icon fa fa-plus "></i>
        <div class="timeline-text-container">
          <span class="timeline-main-text">Create A Note</span>
        </div>
      <% end %>
    </div> -->

    <%= render partial: "users/clients/activity_interaction", collection: @client.interactions, as: :activity_interaction %>
  </div>

</div>

app/views/clients/index.html.erb
<div class="container-center">
  <%= link_to "New Client", new_client_path, class: "c-btn new-interaction-btn" %>

  <ul class="interactions-container">
    <%= render @clients %>
  </ul>

</div>

app/views/clients/new.html.erb
<div class="profile-container">
  <%= form_for @client, html: {class: "simple-form"} do |f| %>
    <div class="form-element">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="form-element">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-element">
      <%= f.label :birthdate %>
      <%= f.date_select :birthdate, {order: [:month, :day, :year], prompt: { day: 'Day', month: 'Month', year: 'Year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: true} %>
    </div>
    <div class="form-element">
      <%= f.label :last_address %>
      <%= f.text_field :last_address %>
    </div>
    <div class="form-element">
      <%= f.label :phone %>
      <%= f.phone_field :phone %>
    </div>
    <div class="form-element">
      <%= f.label :gender %>
      <%= f.text_field :gender %>
    </div>
    <div class="form-element">
      <%= f.label :ssn %>
      <%= f.text_field :ssn %>
    </div>
    <div class="form-element">
      <%= f.label :ethnicity %>
      <%= f.text_field :ethnicity %>
    </div>
    <div class="form-element">
      <%= f.label :education %>
      <%= f.text_field :education %>
    </div>
    <div class="form-element">
      <%= f.label :kid_count %>
      <%= f.number_field :kid_count %>
    </div>
    <div class="form-element">
      <%= f.label :employed %>
      <%= f.check_box :employed %>
    </div>
    <div class="form-element">
      <%= f.label :veteran %>
      <%= f.check_box :veteran %>
    </div>
    <div class="form-element">
      <%= f.label :domestic_assault_victim %>
      <%= f.check_box :domestic_assault_victim %>
    </div>
    <div class="form-element">
      <%= f.label :mental_health %>
      <%= f.check_box :mental_health %>
    </div>
    <div class="form-element">
      <!-- column filler -->
    </div>


    <%= f.submit "Submit", class: "c-btn" %>
  <% end %>
</div>