config/routes.rb
Rails.application.routes.draw do

  root to: "users/interactions#index"

  resources :referrals, only: [:index] do
    collection do
      post 'mark'
      get 'confirmed'
    end
  end

  namespace :users do
    resources :interactions, only: [:index, :show, :new, :create] do
      scope module: 'interactions' do
        resources :events, only: [:create]
      end
    end

    resources :clients, only: [:edit, :update, :index, :new, :create]
    resources :services, only: [:index]
    resources :referrals, only: [:new, :create, :show, :update]
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :provider
  attr_accessor :disqualified, :qualified

  def qualify_and_disqualify(client)
    disqualify(client)
    qualify(client)
  end

  def disqualify(client)
    return false unless name == "Emergency Shelter"
    if female && client.male?
      self.disqualified = "Client is not currently eligible for this service based on gender restrictions.  Please confirm gender."
    elsif male && client.female?
      self.disqualified = "Client is not currently eligible for this service based on gender restrictions.  Please confirm gender."
    elsif ssn && !client.ssn?
      self.disqualified = "Client is not currently eligible for this service due to lack of SS#.  Please confirm with client."
    end
  end

  def qualify(client)
    return false unless name == "Emergency Shelter"
    if family? && client.family?
      self.qualified = "Client is eligible for this service based on family."
    elsif female && client.female?
      self.qualified = "Client is eligible for this service based on gender."
    elsif male && client.male?
      self.qualified = "Client is eligible for this service based on gender."
    elsif ssn && client.ssn?
      self.qualified = "Client is eligible for this service due based on presence of SS#."
    end
  end

  def sort_number
    if qualified.present?
      -1
    elsif disqualified.present?
      1
    else
      0
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    # TODO: auth and constrain to user

    def current_user
      @current_user ||= User.first
    end

    helper_method :current_user
  end
end

app/controllers/users/clients_controller.rb
module Users
  class ClientsController < ApplicationController
    def edit
      @client = Client.find(params[:id])
    end

    def update
      @client = Client.find(params[:id])
      if @client.update_attributes(client_params)
        if params["search_path"].present?
          redirect_to users_services_path(service_name: params["search_path"], interaction_id: @client.interactions.last.id)
        else
          redirect_to users_interactions_path
        end
      else
        render :edit
      end
    end

    def index
      @clients = Client.all
    end

    def new
      @client = Client.new
    end

    def create
      @client = Client.new(client_params)
      if @client.save
        redirect_to users_clients_path
      else
        render :new
      end
    end

    private

      def client_params
        params.require(:client).permit(:phone, :first_name, :last_name, :last_address, :gender, :ssn, :ethnicity, :education, :employed, :veteran, :domestic_assault_victim, :mental_health, :kid_count, :birthdate)
      end
  end
end

app/controllers/users/interactions/events_controller.rb
module Users
  module Interactions
    class EventsController < Users::BaseController

      def create
        @event = Event.create({
          user: current_user,
          interaction: current_interaction,
          content: params[:event][:content],
          source_type: source_type_from_commit
        })

        redirect_to [:users, current_interaction]
      end

      private
      def current_interaction
        @current_interaction ||= Interaction.find(params[:interaction_id])
      end
      helper_method :current_interaction

      # HACK
      def source_type_from_commit
        case params[:commit].to_s.downcase
        when "reply"
          then "sms"
        else
          nil
        end
      end
    end
  end
end

app/controllers/users/interactions_controller.rb
module Users
  class InteractionsController < Users::BaseController

    respond_to :html

    def index
      @interactions = Interaction.active_for(current_user).recent.includes(:events)
      @open_interactions = Interaction.no_replies.no_creator.recent.includes(:events)
    end

    def show
      @interaction = Interaction.find(params[:id])
      @client = @interaction.client
      @event = Event.new(interaction: @interaction, user: current_user)
    end

    def new
      client = Client.where(id: params[:client_id]).first
      if interaction = client.interactions.open.first
        redirect_to users_interaction_path(interaction)
      else
        phone = client.phone if client

        @interaction = Interaction.new(phone: phone)
      end
    end

    def create
      @interaction = Interaction.create(params[:interaction].permit(:phone).merge(status: "open", user: current_user))

      respond_with @interaction, location: [:users, @interaction]
    end

  end
end

app/controllers/users/referrals_controller.rb
module Users
  class ReferralsController < Users::BaseController

    respond_to :html

    def new
      @referral = Referral.new(
        code: Referral.generate_code, interaction_id: params[:interaction_id], service_id: params[:service_id])
    end

    def create
      @referral = Referral.create(params[:referral].permit(:code, :interaction_id, :service_id).merge(status: "open"))

      respond_with @referral, location: [:users, current_interaction]
    end

    def show
      @referral = Referral.find(params[:id])
    end

    def update
      @referral = Referral.find(params[:id])
      @referral.update_attributes(status: "resolved")
      @referral.interaction.update_attributes(status: "resolved")
      redirect_to users_interaction_path(@referral.interaction)
    end

    private
    def current_interaction
      @current_interaction ||= Interaction.find(params[:interaction_id] || params[:referral][:interaction_id])
    end
  end
end

app/controllers/users/services_controller.rb
module Users
  class ServicesController < Users::BaseController

    def index
      @services = Service.where(name: params[:service_name].strip)
      @interaction = Interaction.find(params[:interaction_id])
      @services.each{|s|s.qualify_and_disqualify(@interaction.client)}
      @services = @services.sort_by{|s|s.sort_number}
    end
  end

end

app/views/users/services/_service.html.erb
<div class="provider-container">

  <% if service.disqualified.present? %>
    <p class="disqualified">
      <i class="fa fa-times-circle-o"></i><%= service.disqualified %>
    </p>
  <% elsif service.qualified.present? %>
    <p class="qualified">
      <i class="fa fa-check-circle-o"></i><%= service.qualified %>
    </p>
  <% end %>

  <div class="provider-left">
    <p class="provider-name"><%= service.provider.name %></p>
    <div class="provider-sub-details">
      <a href="#" class='provider-phone'><i class="fa fa-phone"></i><%= service.provider.phone %></a>

      <% if service.provider.website.present? %>
        <a href="#" class='provider-site'><i class="fa fa-globe"></i><%= service.provider.website %></a>
      <% end %>
    </div>

    <div class="provider-service">
      <p class="service-name"><%= service.name %></p>
      <% if service.male? %>
        <p class="service-restriction"><i class="fa fa-male"></i>Male Only</p>
      <% end %>
      <% if service.ssn? %>
        <p class="service-restriction"><i class="fa fa-hashtag"></i>SSN Required</p>
      <% end %>
      <% if service.female? %>
        <p class="service-restriction"><i class="fa fa-female"></i>Female Only</p>
      <% end %>
      <% if service.family? %>
        <p class="service-restriction"><i class="fa fa-child"></i>Family</p>
      <% end %>
      <% if service.sober? %>
        <p class="service-restriction"><i class="fa fa-medkit"></i>Sober Residents Only</p>
      <% end %>

    </div>

    <% if service.provider.services.count > 1 %>
      <div class="provider-addtl-services">
        <p class="service-name"><span class="addtl-services-title">Additional Services:</span> <%= (service.provider.services.map(&:name) - [service.name]).join(", ") %></p>
      </div>
    <% end %>
  </div>

  <div class="provider-right">
    <div class="provider-map-container">
      <div class='provider-map-canvas' data-lat="<%= service.provider.latitude %>" data-lon="<%= service.provider.longitude %>"></div>
      <p class="provider-addy"><%= service.provider.full_address %></p>
    </div>
  </div>

  <div class="clear"></div>
  <div class="provider-btns">
    <%= link_to "refer client", new_users_referral_path(service_id: service.id, interaction_id: @interaction.id), class: "c-btn #{'disabled' if service.disqualified.present?}" %>
  </div>

</div>

app/views/users/services/index.html.erb
<div class="container-center">

  <div class="providers-container">
    <% @services.each do |service| %>
      <%= render partial: "service", locals: {service: service} %>
    <% end %>
  </div>
</div>
<script>

$(document).ready(function(){
  var styles = [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45}]},{"featureType":"road","elementType":"geometry.fill","stylers":[{"color":"#d1b561"},{"lightness":"-15"},{"weight":"1.39"}]},{"featureType":"road","elementType":"labels.text","stylers":[{"color":"#5c5d5f"},{"weight":"0.48"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.highway.controlled_access","elementType":"geometry.fill","stylers":[{"visibility":"on"}]},{"featureType":"road.highway.controlled_access","elementType":"geometry.stroke","stylers":[{"visibility":"off"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#46bcec"},{"visibility":"on"}]}]

  _.each($('.provider-map-canvas'), function(mapCanvas){
    var map = new google.maps.Map(mapCanvas, {
      center: {lat: $(mapCanvas).data('lat'), lng: $(mapCanvas).data('lon')},
      scrollwheel: false,styles: styles, zoom: 14,
      disableDefaultUI: true,
      zoomControl: true
    });
    var marker = new google.maps.Marker({ position: {lat: $(mapCanvas).data('lat'), lng: $(mapCanvas).data('lon')}, map: map });
  });

})

</script>