config/routes.rb
Rails.application.routes.draw do

  root to: "users/interactions#index"

  resources :referrals, only: [:index] do
    collection do
      post 'mark'
      get 'confirmed'
    end
  end

  namespace :users do
    resources :interactions, only: [:index, :show, :new, :create] do
      scope module: 'interactions' do
        resources :events, only: [:create]
      end
    end

    resources :clients, only: [:edit, :update, :index, :new, :create]
    resources :services, only: [:index]
    resources :referrals, only: [:new, :create, :show, :update]
  end
end

app/views/layouts/_header.html.erb
<div id="header">
  <div class="inner-header">
    <%= link_to root_path, id: "header-home-link" do %>
      <span>Advocate</span>
    <% end %>
    <ul class="primary-navigation">
      <li><%= link_to "Interactions", users_interactions_path %></li>
      <li><%= link_to "Clients", users_clients_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Advocate</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= current_user_token %>

  <script src="https://use.fontawesome.com/370cf7d40a.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-b8ebWEM6fpafSwau-KnaVlxyNmKcDSo"></script>
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
  
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</head>
<body>

  <%= render partial: "layouts/header" %>

  <div class="page-container">
    <%= yield %>
  </div>
</body>
</html>